### ISSUE TITLE
Tagging?

### ISSUE THREAD

**Issue by Robinlovelace** [geocompr/docker#11]
With the current set-up we don't do any tagging of different versions. However it would improve reproducibility if we could add tags making it easier for people to get images produced at a particular data/release. The action on which our Docker actions are based enable tagging but I wasn't sure how best to implement this https://github.com/docker/build-push-action/blob/master/docs/advanced/tags-labels.md

Any comments/suggestions on this very welcome.

**Comment by Robinlovelace** [comment]
I think I've figured out how to do this. Test rep: 

Results: https://hub.docker.com/repository/docker/robinlovelace/testtags/tags?page=1&ordering=last_updated

Only question, what should the images be called?

I vote something like this (for the suggests container):

```
          tags: |
            type=raw,value=suggests
            type=raw,value=suggests_,suffix=sha

```

Result: 

![image](https://user-images.githubusercontent.com/1825120/135698435-72632bdc-e175-4d17-a6f7-4ba7286dcbff.png)

See results of these tests: https://github.com/Robinlovelace/dockertags

More options: https://github.com/docker/metadata-action#tags-input

**Comment by Robinlovelace** [comment]
Request for feedback: do you have any thoughts/preferences on this @Nowosad or @jannes-m ?

I think

```bash
suggests_{date} # for scheduled builds
suggests_{commit} # for updates to this repo, and
suggests # for rolling updates to latest version
```

And same pattern for `latest`, `minimal`, `qgis` and other dockerfiles is fine. Plan: try that today, see if it works, and then shift to a weekly build cycle if it goes well to reduce the number of images flying around.

**Comment by Nowosad** [comment]
Sounds good.

**Comment by Robinlovelace** [comment]
Progress on this after the commit above, we now have a permalink for the latest `latest` tagged image.

![image](https://user-images.githubusercontent.com/1825120/135713916-53a92984-c1f2-436b-9d75-dd7cf0ae4c53.png)

Source: https://hub.docker.com/r/geocompr/geocompr/tags?page=1&ordering=last_updated

**Comment by Robinlovelace** [comment]
In terms of testing, I just ran the following commend.

```bash
docker pull geocompr/geocompr:latest_d8d0df4
```

Seems to work :tada:

**Comment by Robinlovelace** [comment]
Next steps: diagnose cause of failing workflow and add tags to all images.

**Comment by Robinlovelace** [comment]
The tags with times seem to be working... 

![image](https://user-images.githubusercontent.com/1825120/135743688-1ac044e3-d5b9-4809-939e-e8f05f237dba.png)

**Comment by Robinlovelace** [comment]
Just tested:

```bash
docker pull geocompr/geocompr:latest_2021-10-03
```

I think we can close this issue now but we should document the new tagging system in the README.
