### ISSUE TITLE
rocker 

### ISSUE THREAD

**Issue by Nowosad** [geocompr/docker#13]
@Robinlovelace do I understand correctly that the geocompr images are based on rocker-org/geospatial? If so, https://github.com/rocker-org/geospatial uses very old R version and has not been updated in ~2 years. Should we do something with it?

**Comment by Robinlovelace** [comment]
No need to do anything because that repo has been superseded by this: https://github.com/rocker-org/rocker-versioned2

One idea was for us to contribute upstream so I'll leave this open to discuss that and other geocompr/rocker possibilities, cc @cboettig (apologies for all the nudges/tags btw).

**Comment by Robinlovelace** [comment]
Any way we can support Rocker, I'm keen to hear, you guys Rock!

**Comment by cboettig** [comment]
We're always happy for PRs / requests / etc in the rocker geospatial stacks!  

As you know, the standard geospatial images are mostly configured by:

- https://github.com/rocker-org/rocker-versioned2/blob/master/scripts/install_geospatial.sh

We also have `:ubuntugis` (focal PPA) https://github.com/rocker-org/rocker-versioned2/blob/master/scripts/install_geospatial_unstable.sh, and `dev-osgeo` https://github.com/rocker-org/rocker-versioned2/blob/master/scripts/dev_osgeo.sh configs.

I think we will need to update `geospatial.sh` R package list again soon to accommodate the phasing out of the old-gen packages and add in some of the new packages.  

Updates to any of those config files are more than welcome!  


`geospatial.sh` is also run on the `ml-verse` images for anyone who needs geo libs + python + cuda, but those are very big images!

**Comment by Robinlovelace** [comment]
This is now fixed I think.
