### ISSUE TITLE
Installation of movingpandas fails on geocompr/geocompr:python image

### ISSUE THREAD

**Issue by Robinlovelace** [geocompr/docker#22]
For some reason. Logs: https://github.com/geocompr/docker/runs/5431901131?check_suite_focus=true#step:8:695

Heads-up @anitagraser plan for now is to remove movingpandas and add later. I'll keep this issue open to track it.

I may have made a silly mistake, quite likely as currently my Python dev skills amount to guesswork!

**Comment by anitagraser** [comment]
> Proj version 6.3.1 is installed, but cartopy requires at least version 8.0.0.

is the same error I currently get on readthedocs ... I think I'll have to sit this one out until the dependencies resolve themselves again.

**Comment by Robinlovelace** [comment]
Self fixing issues, the best type, except when they take ages. Will be patient!

**Comment by anitagraser** [comment]
Managed to fix the docs by imitating GeoPandas and switching from conda to mamba: https://github.com/anitagraser/movingpandas/pull/197/files

**Comment by Robinlovelace** [comment]
Good to know. I'm guessing it may be linked to OSGeo library versions, primarily PROJ 8.0.0 required by cartopy? That may be fixed upstream in the rocker/geospatial images, although I'll still need to adjust the `geocompr/geocompr:python` image after testing the fix: https://github.com/rocker-org/rocker-versioned2/issues/376 - we could create another image for testing but for now this seems like a reasonable solution.
