### ISSUE TITLE
Switch to Rocker's new host location for geospatial images

### ISSUE THREAD

**Issue by Robinlovelace** [geocompr/docker#30]
https://github.com/rocker-org/rocker-versioned2/pkgs/container/geospatial

**Comment by Robinlovelace** [comment]
OK no, they are still available: https://hub.docker.com/r/rocker/geospatial/tags

**Comment by Nowosad** [comment]
The question is -- for how long we can expect the older version to be maintained?

**Comment by Robinlovelace** [comment]
> how long we can expect the older version to be maintained?

https://github.com/rocker-org/rocker-versioned2/issues/524
