### ISSUE TITLE
Auto build Docker containers

### ISSUE THREAD

**Issue by Robinlovelace** [geocompr/docker#9]
As discussed with @Nowosad currently the Docker images are rebuilt every time one of us pushes to the repo. This is not ideal. Any ideas for getting a more automated system going? It's tricky because DockerHub only triggers builds when it detects commits in this repo I think, so I was thinking of a cron job on my computer, but that is not an ideal solution. Suggestions welcome.

**Comment by Robinlovelace** [comment]
Update on this, I think it is worth switching to hosting the images on github.

This works:

```
docker run ghcr.io/jonashackt/hello-world
```

The equivalent could be:

```
docker run ghcr.io/geocompr/docker
```

Or similar...

Heads-up @Nowosad I think this may be the most useful task I can work on but may take some time. Good post on this: https://blog.codecentric.de/en/2021/03/github-container-registry/

**Comment by Robinlovelace** [comment]
Finally taking action on this. Heads-up @Nowosad it seems something is happening! https://github.com/geocompr/docker/runs/3737156838

**Comment by Robinlovelace** [comment]
Approach documented here worked :tada: 

1 down, n to go!

![image](https://user-images.githubusercontent.com/1825120/135165066-17ec1b1d-a7d7-4497-976e-239ddd6d53d9.png)

**Comment by Robinlovelace** [comment]
https://github.com/docker/build-push-action#path-context

**Comment by Robinlovelace** [comment]
Update, this should now work with images hosted on ghcr.io and DockerHub: https://github.com/geocompr/docker/pkgs/container/docker

**Comment by Robinlovelace** [comment]
I think this is done. We can leave it a day or 2 to see if the daily builds work. Hope so! I may switch those to be weekly builds...

**Comment by Nowosad** [comment]
@Robinlovelace looks awesome. Next step (challenge) is to use the image to build the book (instead of installing all of the dependences in each repo separately).

**Comment by Robinlovelace** [comment]
I guess something like this will do it:

```
jobs:
  build:
    runs-on: ubuntu-latest
    container: geocompr/geocompr:qgis-ext
```

Source: https://github.com/Robinlovelace/geocompr/blob/main/.github/workflows/qgis-ext.yaml

Those additional yml files can be deleted/revived. I think a lot of the testing work can be handled by this Docker repo now - it's already discovered that the book does not build on 'ubuntugis' for some reason...

**Comment by Robinlovelace** [comment]
Failing code in maybe outdated dev-osgeo-buildbook image FYI (I have put this workflow file in a separate folder to prevent build errors for now):

```
#7 73.30 Quitting from lines 126-139 (04-spatial-operations.Rmd) 
#7 73.30 Error in parse(text = x, srcfile = src) : 
#7 73.30   attempt to use zero-length variable name
#7 73.30 Calls: local ... <Anonymous> -> parse_all -> parse_all.character -> parse
#7 73.31 
#7 73.31 Execution halted
#7 73.34 Error in Rscript_render(f, render_args, render_meta, add1, add2) : 
#7 73.34   Failed to compile 04-spatial-operations.Rmd
```

Source: https://github.com/geocompr/docker/runs/3738897231#step:7:16734

I propose that we do not investigate that further for now, we can investigate things like that later and I think the qgis images are a higher priority. Will re-test now, I was having some issues installing QGIS in the containers :crossed_fingers: that's fixed now, will test!

**Comment by Robinlovelace** [comment]
Update, the `qgis` tag still does not have a recent version of QGIS and I'm not sure why... Reprex:

```
docker pull geocompr/geocompr:qgis
docker run -e PASSWORD=pw --rm -ti geocompr/geocompr:qgis /bin/bash
root@36635b57372e:/# qgis --version
QGIS 3.10.4-A Coruña 'A Coruña' (exported)
root@36635b57372e:/# exit
```

**Comment by jannes-m** [comment]
I thought you hosted the images now on github.

**Comment by Robinlovelace** [comment]
We do, the images are now hosted in 2 places for redundancy/resilience. The following reprex should work:

```
docker pull ghcr.io/geocompr/geocompr:minimal
docker run -e PASSWORD=pw --rm -ti geocompr/geocompr:qgis /bin/bash
```

**Comment by Robinlovelace** [comment]
```
docker run -e PASSWORD=pw --rm -ti ghcr.io/geocompr/geocompr:qgis /bin/bash
Unable to find image 'ghcr.io/geocompr/geocompr:qgis' locally
qgis: Pulling from geocompr/geocompr
Digest: sha256:33ce48964fadce8ea58e10b7a2bc72ee8bc707d9b397f69fb52ad7a85a6d7dc8
Status: Downloaded newer image for ghcr.io/geocompr/geocompr:qgis
root@95a7e462c147:/# qgis --version
QGIS 3.10.4-A Coruña 'A Coruña' (exported)
```

**Comment by Nowosad** [comment]
We are almost there - https://github.com/Robinlovelace/geocompr/runs/3746812202?check_suite_focus=true. 

@Robinlovelace two questions:

1. Which image should I use?
2. Could this image also contain packages suggested by geocompkg?

**Comment by Robinlovelace** [comment]
> We are almost there - https://github.com/Robinlovelace/geocompr/runs/3746812202?check_suite_focus=true.

:tada: 


> 
> @Robinlovelace two questions:

Good questions, I'm thinking:

> 
>     1. Which image should I use?

geocompr/geocompr:minimal should be the quickest to build and be most up-to-date. geocompr/geocompr deliberately has the .zip file in there so includes duplicate data.

> 
>     2. Could this image also contain packages suggested by geocompkg?

Good question, yes but I think in the interests of modularity and bandwidth that it would make sense to create a new image, e.g. called geocompr/geocompr:suggested.

You can follow the pattern of the other .yml/Dockerfiles if you want to give that a shot or I can give it a go at some point.

**Comment by Robinlovelace** [comment]
The idea is the the Suggests are not needed to build the book so I would stick with the minimal version for the regular builds. Ideally, we would reduce the number of Imports and remove `sp`, `rgeos` and other rarely needed packages at some point in the not-too-distant future!

**Comment by Robinlovelace** [comment]
>   there is no package called ‘mapdeck’

The annoying thing with that is that `mapdeck` is not needed. I think the code fails because `bookdown` is trying to cite it... So my suggestion for now to reduce deps would be to change code in the .Rmds that makes it not required. Happy to hear alternative points of view though...

**Comment by Nowosad** [comment]
Several packages from Suggests are needed to build the book now. This is related to the new theme (or maybe new search engine?)? I have spent some time searching, but was unable to find anything about why this is needed for packages we do not run, and is it possible to disable this....

**Comment by Robinlovelace** [comment]
https://github.com/geocompr/docker/commit/8bfdd3f9253a93a4fdc4e4d1ae6d28f485fbba04 should make https://github.com/Robinlovelace/geocompr/pull/652 work in ~30 minutes.
